export const genresEN = [
    { id: 28, name: "Action", emoji: "🔥" },
    { id: 12, name: "Adventure", emoji: "🗺️" },
    { id: 16, name: "Animation", emoji: "🎨" },
    { id: 35, name: "Comedy", emoji: "😂" },
    { id: 80, name: "Crime", emoji: "🕵️" },
    { id: 99, name: "Documentary", emoji: "🎥" },
    { id: 18, name: "Drama", emoji: "🎭" },
    { id: 10751, name: "Family", emoji: "👪" },
    { id: 14, name: "Fantasy", emoji: "🧙‍♂️" },
    { id: 36, name: "History", emoji: "📜" },
    { id: 27, name: "Horror", emoji: "👻" },
    { id: 10402, name: "Music", emoji: "🎶" },
    { id: 9648, name: "Mystery", emoji: "🕵️‍♂️" },
    { id: 10749, name: "Romance", emoji: "❤️" },
    { id: 878, name: "Science Fiction", emoji: "🚀" },
    { id: 10770, name: "TV Movie", emoji: "📺" },
    { id: 53, name: "Thriller", emoji: "🔪" },
    { id: 10752, name: "War", emoji: "⚔️" },
    { id: 37, name: "Western", emoji: "🤠" },
];

export const genresES = [
    { id: 28, name: "Acción", emoji: "🔥" },
    { id: 12, name: "Aventura", emoji: "🗺️" },
    { id: 16, name: "Animación", emoji: "🎨" },
    { id: 35, name: "Comedia", emoji: "😂" },
    { id: 80, name: "Crimen", emoji: "🕵️" },
    { id: 99, name: "Documental", emoji: "🎥" },
    { id: 18, name: "Drama", emoji: "🎭" },
    { id: 10751, name: "Familia", emoji: "👪" },
    { id: 14, name: "Fantasía", emoji: "🧙‍♂️" },
    { id: 36, name: "Historia", emoji: "📜" },
    { id: 27, name: "Terror", emoji: "👻" },
    { id: 10402, name: "Música", emoji: "🎶" },
    { id: 9648, name: "Misterio", emoji: "🕵️‍♂️" },
    { id: 10749, name: "Romance", emoji: "❤️" },
    { id: 878, name: "Ciencia ficción", emoji: "🚀" },
    { id: 10770, name: "Película de TV", emoji: "📺" },
    { id: 53, name: "Suspense", emoji: "🔪" },
    { id: 10752, name: "Bélica", emoji: "⚔️" },
    { id: 37, name: "Western", emoji: "🤠" },
];
